spring.application.name=gestorNF

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.config.import=optional:file:.env.properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

envio.email.remetente=${EMAIL_USERNAME}
envio.email.nomeRemetente=GestorNF
envio.email.url-verificacao=${BACKEND_URL}/usuario/verificar-email
envio.email.url-recuperacao=${FRONTEND_URL}/redefinir-senha

server.port=${PORT:8080}