spring.application.name=gestorNF

spring.datasource.url=jdbc:postgresql://localhost:5432/db_notas_fiscais
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.config.import=optional:file:.env.properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

envio.email.remetente=${EMAIL_USERNAME}
envio.email.nomeRemetente=GestorNF
envio.email.url-verificacao=http://localhost:8080/usuario/verificar-email
envio.email.url-recuperacao=http://localhost:3000/redefinir-senha